### ISSUE TITLE
Documentation site is down (403)

### ISSUE THREAD

**Issue by equake** [Pylons/pylonsproject.org#75] opened 2020-04-22 20:14 UTC
Hi, 
I'm having trouble reaching https://docs.pylonsproject.org/

```
403 Forbidden
cloudflare
```

Thanks.

**Comment by stevepiercy** [comment] 2020-04-22 21:59
It's not a valid URL. You need to specify a project, for example:
https://docs.pylonsproject.org/projects/pyramid/en/latest/

**Comment by mmerickel** [comment] 2020-04-22 22:16
Your valid URL is not working @stevepiercy .

**Comment by stevepiercy** [comment] 2020-04-22 22:39
Meh, cache. Can't look into it for a couple hours.

**Comment by stevepiercy** [comment] 2020-04-23 00:57
Duplicate of https://github.com/Pylons/pyramid/issues/3574

**Closed by stevepiercy** 2020-04-23 00:57 UTC
